[project]
name = "s3tokenizers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "librosa>=0.11.0",
    "pyyaml>=6.0.3",
    "s3tokenizer>=0.3.0",
    "torch>=2.10.0",
]

[project.scripts]
s3tokenizers = "s3tokenizers:main"
s3tokenizers_test = "s3tokenizers.app:s3tokenizers_test"
s3tokenizers_streaming_test = "s3tokenizers.app:s3tokenizers_streaming_test"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
