tokenizer : &tokenizer
  
  model-name : speech_tokenizer_v2_25hz
  sample-rate : 16000
  n_fft : 400
  padding : 0 
  hop_length : 160

mel-spec-model : &mel-spec-model
  n-fft : 1920 
  n-mels : 80
  sample-rate : 24000
  hop-size : 480
  win-size : 1920
  win-length : 1920
  f-min : 0
  f-max : 8000
  normalized : False
  onesided : True
  center : False
  pad-mode : reflect   

  spec-calc : mod
  log : natural

  drop-last-spec : False

  clip-val : 0.00001

mel-spec-tokenizer : &mel-spec-tokenizer
  n-fft : 400 
  n-mels : 128
  sample-rate : 16000
  hop-size : 160
  win-size : 400
  win-length : 400
  center : False
  normalized : False

  spec-calc : power
  log : log10

  drop-last-spec : True

  clip-val : 0.0000000001

  addition-amount : 4
  division-amount : 4


tests : 

  s3gen-streaming : 
    input-file-path : /teamspace/studios/this_studio/output.wav
    chunk-size : 6400
    reference-audio-path : /teamspace/studios/this_studio/ElevenLabs_2025-06-05T07_18_58_Rachel_pre_sp100_s50_sb75_se0_b_m2.mp3

    tokenizer : 
      <<: *tokenizer

    mel-spec-model : 
      <<: *mel-spec-model

    mel-spec-tokenizer : 
      <<: *mel-spec-tokenizer

    generation : 