audio_tokenizer : &audio_tokenizer
  
  model-name : speech_tokenizer_v2_25hz
  sample-rate : 16000
  n_fft : 400
  padding : 0 
  hop_length : 160

mel-spec : &mel-spec
  n-fft : 1920 
  num-mels : 80
  sample-rate : 24000
  hop-size : 480
  win-size : 1920
  f-min : 0
  f-max : 8000
  center : False
  normalized : False
  onesided : True

  c : 1
  clip-val : 0.000001

tokenizer : &tokenizer
  vocab-file-path : assets/tokenizers_/vocab.json

  pre-process : 
    punctuations : 
      - ['...' , ',']
      - ['…' , ',']
      - [':' , ',']
      - [' -' , ',']
      - [';' , ',']
      - ['_' , ',']
      - [' ,' , ',']
      - ['“' , '\' ]
      - ['”' , '\']
      - ['‘' , "'"]
      - ['’' , "'"]

    allowed-endings : [
      '!', '?', '.', ',', ';', ':', '-', '_', '…'
    ]

    default-ending : '.'

  tokens : 
    space : '[SPACE]'
    unk : '[UNK]'
    eot : '[STOP]'
    sot : '[START]'

voice-encoder : &voice-encoder
  model-path : assets/models/voice_encoder/ve.pt

t3 : &t3
  model-path : /teamspace/studios/this_studio/models/t3_mtl23ls_v2.safetensors
  # model-path : /teamspace/studios/this_studio/models/t3_23lang.safetensors

tests : 

  t3-generation : 
    input-file-path : /teamspace/studios/this_studio/output.wav
    chunk-size : 6400
    reference-audio-path : /teamspace/studios/this_studio/output.wav

    audio_tokenizer : 
      <<: *audio_tokenizer

    mel-spec : 
      <<: *mel-spec

    tokenizer : 
      <<: *tokenizer

    generation : 

    voice-encoder : 
      <<: *voice-encoder

    attributes : 
      exaggeration : 1.0

    t3 : 
      <<: *t3