[project]
name = "t3tokenizers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "modules",
    "pyyaml>=6.0.3",
    "s3gen",
    "s3tokenizer>=0.3.0",
    "tokenizers>=0.22.2",
    "torch>=2.10.0",
    "transformers>=5.2.0",
]

[project.scripts]
t3tokenizers = "t3tokenizers.app:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
modules = { workspace = true }
s3gen = { workspace = true }
