tokenizer : &tokenizer
  
  model-name : speech_tokenizer_v2_25hz
  sample-rate : 16000
  n_fft : 400
  padding : 0 
  hop_length : 160

mel-spec : &mel-spec
  n-fft : 1920 
  num-mels : 80
  sample-rate : 24000
  hop-size : 480
  win-size : 1920
  f-min : 0
  f-max : 8000
  center : False
  normalized : False
  onesided : True

  c : 1
  clip-val : 0.000001

tests : 
  s3tokenizer : 
    input-file-path : /teamspace/studios/this_studio/output.wav
    sample-rate : 16000

    tokenizer : 
      <<: *tokenizer

  s3tokenizer-streaming : 
    input-file-path : /teamspace/studios/this_studio/output.wav
    chunk-size : 6400

    tokenizer : 
      <<: *tokenizer

  s3gen-streaming : 
    input-file-path : /teamspace/studios/this_studio/output.wav
    chunk-size : 6400
    reference-audio-path : /teamspace/studios/this_studio/output.wav

    tokenizer : 
      <<: *tokenizer

    mel-spec : 
      <<: *mel-spec

    generation : 





sample-rate : 16000
file-name : /teamspace/studios/this_studio/ElevenLabs_2026-01-01T12_10_26_Liam - Energetic, Social Media Creator_pre_sp100_s50_sb75_v3.mp3


upsample-conformer-encoder : 
  output-size : 512 
  attention-heads : 8
  linear-units : 2048 
  num-blocks : 6
  dropout-rate : 0.1
  positional-dropout-rate : 0.1
  attention-dropout-rate : 0.1
  normalize-before : True
  input-layer : linear
  pos-enc-layer-type : rel_pos_espnet
  self-attention-layer-type : rel_selfattn
  input-size : 512
  use-cnn-module : False
  macron-style : False

esitmator : 
  in-channels : 320
  out-channels : 80
  causal : True
  channels : [256]
  dropout : 0.0
  attention-head-dim : 64
  n-blocks : 4
  num-mid-blocks : 12
  num-heads : 8
  act-fn : gelu

speak-emb-dim : 80

